// This file is generated automatically by Next.js
// Do not edit this file manually

type AppRoutes = "/" | "/about" | "/analytics" | "/booking/confirmation" | "/comfort-match" | "/compare" | "/configurator/[slug]" | "/contact" | "/dealers" | "/dealers/[id]" | "/furniture" | "/furniture/[slug]" | "/handover" | "/inspiration/rooms" | "/materials" | "/my-musterring" | "/my-musterring/projects/[id]" | "/partner" | "/partner/configurator" | "/partner/configurator/[slug]" | "/partner/login" | "/partner/orders" | "/partner/products" | "/partner/projects" | "/partner/quotes" | "/partner/resources" | "/presentation" | "/privacy" | "/room-composer" | "/room-composer/upload" | "/search" | "/visual-search" | "/will-it-fit/[slug]"
type AppRouteHandlerRoutes = "/api/ai/advisor" | "/api/ai/alternatives" | "/api/ai/comfort" | "/api/ai/configuration" | "/api/ai/image" | "/api/ai/material-advice" | "/api/ai/retailer-summary" | "/api/ai/room" | "/api/ai/search" | "/api/ai/voice-command" | "/api/demo/handover" | "/api/demo/upload-metadata" | "/api/partner/login" | "/api/partner/logout"
type PageRoutes = never
type LayoutRoutes = "/" | "/partner"
type RedirectRoutes = never
type RewriteRoutes = never
type Routes = AppRoutes | PageRoutes | LayoutRoutes | RedirectRoutes | RewriteRoutes | AppRouteHandlerRoutes


interface ParamMap {
  "/": {}
  "/about": {}
  "/analytics": {}
  "/api/ai/advisor": {}
  "/api/ai/alternatives": {}
  "/api/ai/comfort": {}
  "/api/ai/configuration": {}
  "/api/ai/image": {}
  "/api/ai/material-advice": {}
  "/api/ai/retailer-summary": {}
  "/api/ai/room": {}
  "/api/ai/search": {}
  "/api/ai/voice-command": {}
  "/api/demo/handover": {}
  "/api/demo/upload-metadata": {}
  "/api/partner/login": {}
  "/api/partner/logout": {}
  "/booking/confirmation": {}
  "/comfort-match": {}
  "/compare": {}
  "/configurator/[slug]": { "slug": string; }
  "/contact": {}
  "/dealers": {}
  "/dealers/[id]": { "id": string; }
  "/furniture": {}
  "/furniture/[slug]": { "slug": string; }
  "/handover": {}
  "/inspiration/rooms": {}
  "/materials": {}
  "/my-musterring": {}
  "/my-musterring/projects/[id]": { "id": string; }
  "/partner": {}
  "/partner/configurator": {}
  "/partner/configurator/[slug]": { "slug": string; }
  "/partner/login": {}
  "/partner/orders": {}
  "/partner/products": {}
  "/partner/projects": {}
  "/partner/quotes": {}
  "/partner/resources": {}
  "/presentation": {}
  "/privacy": {}
  "/room-composer": {}
  "/room-composer/upload": {}
  "/search": {}
  "/visual-search": {}
  "/will-it-fit/[slug]": { "slug": string; }
}


export type ParamsOf<Route extends Routes> = ParamMap[Route]

interface LayoutSlotMap {
  "/": never
  "/partner": never
}


export type { AppRoutes, PageRoutes, LayoutRoutes, RedirectRoutes, RewriteRoutes, ParamMap, AppRouteHandlerRoutes }

declare global {
  /**
   * Props for Next.js App Router page components
   * @example
   * ```tsx
   * export default function Page(props: PageProps<'/blog/[slug]'>) {
   *   const { slug } = await props.params
   *   return <div>Blog post: {slug}</div>
   * }
   * ```
   */
  interface PageProps<AppRoute extends AppRoutes> {
    params: Promise<ParamMap[AppRoute]>
    searchParams: Promise<Record<string, string | string[] | undefined>>
  }

  /**
   * Props for Next.js App Router layout components
   * @example
   * ```tsx
   * export default function Layout(props: LayoutProps<'/dashboard'>) {
   *   return <div>{props.children}</div>
   * }
   * ```
   */
  type LayoutProps<LayoutRoute extends LayoutRoutes> = {
    params: Promise<ParamMap[LayoutRoute]>
    children: React.ReactNode
  } & {
    [K in LayoutSlotMap[LayoutRoute]]: React.ReactNode
  }

  /**
   * Context for Next.js App Router route handlers
   * @example
   * ```tsx
   * export async function GET(request: NextRequest, context: RouteContext<'/api/users/[id]'>) {
   *   const { id } = await context.params
   *   return Response.json({ id })
   * }
   * ```
   */
  interface RouteContext<AppRouteHandlerRoute extends AppRouteHandlerRoutes> {
    params: Promise<ParamMap[AppRouteHandlerRoute]>
  }
}
