// This file is generated automatically by Next.js
// Do not edit this file manually
// This file validates that all pages and layouts export the correct types

import type { AppRoutes, LayoutRoutes, ParamMap, AppRouteHandlerRoutes } from "./routes.js"
import type { ResolvingMetadata, ResolvingViewport } from "next/types.js"
import type { NextRequest } from 'next/server.js'

type AppPageConfig<Route extends AppRoutes = AppRoutes> = {
  default: React.ComponentType<{ params: Promise<ParamMap[Route]> } & any> | ((props: { params: Promise<ParamMap[Route]> } & any) => React.ReactNode | Promise<React.ReactNode> | never | void | Promise<void>)
  generateStaticParams?: (props: { params: ParamMap[Route] }) => Promise<any[]> | any[]
  generateMetadata?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingMetadata
  ) => Promise<any> | any
  generateViewport?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingViewport
  ) => Promise<any> | any
  metadata?: any
  viewport?: any
}

type LayoutConfig<Route extends LayoutRoutes = LayoutRoutes> = {
  default: React.ComponentType<LayoutProps<Route>> | ((props: LayoutProps<Route>) => React.ReactNode | Promise<React.ReactNode> | never | void | Promise<void>)
  generateStaticParams?: (props: { params: ParamMap[Route] }) => Promise<any[]> | any[]
  generateMetadata?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingMetadata
  ) => Promise<any> | any
  generateViewport?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingViewport
  ) => Promise<any> | any
  metadata?: any
  viewport?: any
}

type RouteHandlerConfig<Route extends AppRouteHandlerRoutes = AppRouteHandlerRoutes> = {
  GET?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  POST?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  PUT?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  PATCH?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  DELETE?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  HEAD?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  OPTIONS?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
}


// Validate ../../app/about/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/about">> = Specific
  const handler = {} as typeof import("../../app/about/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/analytics/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/analytics">> = Specific
  const handler = {} as typeof import("../../app/analytics/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/booking/confirmation/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/booking/confirmation">> = Specific
  const handler = {} as typeof import("../../app/booking/confirmation/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/comfort-match/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/comfort-match">> = Specific
  const handler = {} as typeof import("../../app/comfort-match/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/compare/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/compare">> = Specific
  const handler = {} as typeof import("../../app/compare/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/configurator/[slug]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/configurator/[slug]">> = Specific
  const handler = {} as typeof import("../../app/configurator/[slug]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/contact/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/contact">> = Specific
  const handler = {} as typeof import("../../app/contact/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/dealers/[id]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dealers/[id]">> = Specific
  const handler = {} as typeof import("../../app/dealers/[id]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/dealers/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dealers">> = Specific
  const handler = {} as typeof import("../../app/dealers/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/furniture/[slug]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/furniture/[slug]">> = Specific
  const handler = {} as typeof import("../../app/furniture/[slug]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/furniture/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/furniture">> = Specific
  const handler = {} as typeof import("../../app/furniture/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/handover/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/handover">> = Specific
  const handler = {} as typeof import("../../app/handover/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/inspiration/rooms/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/inspiration/rooms">> = Specific
  const handler = {} as typeof import("../../app/inspiration/rooms/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/materials/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/materials">> = Specific
  const handler = {} as typeof import("../../app/materials/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/my-musterring/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/my-musterring">> = Specific
  const handler = {} as typeof import("../../app/my-musterring/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/my-musterring/projects/[id]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/my-musterring/projects/[id]">> = Specific
  const handler = {} as typeof import("../../app/my-musterring/projects/[id]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/">> = Specific
  const handler = {} as typeof import("../../app/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/partner/(workspace)/configurator/[slug]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/partner/configurator/[slug]">> = Specific
  const handler = {} as typeof import("../../app/partner/(workspace)/configurator/[slug]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/partner/(workspace)/configurator/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/partner/configurator">> = Specific
  const handler = {} as typeof import("../../app/partner/(workspace)/configurator/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/partner/(workspace)/orders/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/partner/orders">> = Specific
  const handler = {} as typeof import("../../app/partner/(workspace)/orders/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/partner/(workspace)/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/partner">> = Specific
  const handler = {} as typeof import("../../app/partner/(workspace)/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/partner/(workspace)/products/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/partner/products">> = Specific
  const handler = {} as typeof import("../../app/partner/(workspace)/products/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/partner/(workspace)/projects/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/partner/projects">> = Specific
  const handler = {} as typeof import("../../app/partner/(workspace)/projects/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/partner/(workspace)/quotes/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/partner/quotes">> = Specific
  const handler = {} as typeof import("../../app/partner/(workspace)/quotes/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/partner/(workspace)/resources/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/partner/resources">> = Specific
  const handler = {} as typeof import("../../app/partner/(workspace)/resources/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/partner/login/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/partner/login">> = Specific
  const handler = {} as typeof import("../../app/partner/login/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/presentation/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/presentation">> = Specific
  const handler = {} as typeof import("../../app/presentation/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/privacy/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/privacy">> = Specific
  const handler = {} as typeof import("../../app/privacy/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/room-composer/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/room-composer">> = Specific
  const handler = {} as typeof import("../../app/room-composer/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/room-composer/upload/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/room-composer/upload">> = Specific
  const handler = {} as typeof import("../../app/room-composer/upload/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/search/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/search">> = Specific
  const handler = {} as typeof import("../../app/search/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/visual-search/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/visual-search">> = Specific
  const handler = {} as typeof import("../../app/visual-search/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/will-it-fit/[slug]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/will-it-fit/[slug]">> = Specific
  const handler = {} as typeof import("../../app/will-it-fit/[slug]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/ai/advisor/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/ai/advisor">> = Specific
  const handler = {} as typeof import("../../app/api/ai/advisor/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/ai/alternatives/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/ai/alternatives">> = Specific
  const handler = {} as typeof import("../../app/api/ai/alternatives/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/ai/comfort/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/ai/comfort">> = Specific
  const handler = {} as typeof import("../../app/api/ai/comfort/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/ai/configuration/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/ai/configuration">> = Specific
  const handler = {} as typeof import("../../app/api/ai/configuration/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/ai/image/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/ai/image">> = Specific
  const handler = {} as typeof import("../../app/api/ai/image/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/ai/material-advice/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/ai/material-advice">> = Specific
  const handler = {} as typeof import("../../app/api/ai/material-advice/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/ai/retailer-summary/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/ai/retailer-summary">> = Specific
  const handler = {} as typeof import("../../app/api/ai/retailer-summary/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/ai/room/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/ai/room">> = Specific
  const handler = {} as typeof import("../../app/api/ai/room/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/ai/search/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/ai/search">> = Specific
  const handler = {} as typeof import("../../app/api/ai/search/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/ai/voice-command/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/ai/voice-command">> = Specific
  const handler = {} as typeof import("../../app/api/ai/voice-command/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/demo/handover/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/demo/handover">> = Specific
  const handler = {} as typeof import("../../app/api/demo/handover/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/demo/upload-metadata/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/demo/upload-metadata">> = Specific
  const handler = {} as typeof import("../../app/api/demo/upload-metadata/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/partner/login/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/partner/login">> = Specific
  const handler = {} as typeof import("../../app/api/partner/login/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/partner/logout/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/partner/logout">> = Specific
  const handler = {} as typeof import("../../app/api/partner/logout/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}





// Validate ../../app/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/">> = Specific
  const handler = {} as typeof import("../../app/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/partner/(workspace)/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/partner">> = Specific
  const handler = {} as typeof import("../../app/partner/(workspace)/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}
